# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, filepath, genericAeson, happstackServer, hxt
, jsonSchema, monadControl, mtl, regular, regularXmlpickler
, restCore, restGen, restHappstack, safe, stm, text, time
, transformers, transformersBase, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "rest-example";
  version = "0.1.2";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson filepath genericAeson happstackServer hxt jsonSchema
    monadControl mtl regular regularXmlpickler restCore restGen
    restHappstack safe stm text time transformers transformersBase
    unorderedContainers
  ];
  meta = {
    homepage = "http://www.github.com/silkapp/rest";
    description = "Example project for rest";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
